##############################################################################
#  Copyright Christopher Kormanyos 2023 - 2024.
#  Distributed under The Unlicense.

name: ti84-ref_app
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  gcc-build-native:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: get-sdcc-toolchain
        run: |
          mkdir ../sdcc-root
          cd ../sdcc-root
          wget --no-check-certificate https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/4.4.0/sdcc-4.4.0-amd64-unknown-linux2.5.tar.bz2
          tar -xjf sdcc-4.4.0-amd64-unknown-linux2.5.tar.bz2
      - name: build-and-verify-refapp
        run: |
          cd build
          PATH=../../sdcc-root/sdcc-4.4.0/bin:"$PATH"
          sdcc -v
          make TYP_OS=UNIX all
          echo 'build-and-verify-refapp partial verify result'
          ls -la ../bin/refapp.8xp
